# Use the official Python image from Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the source code into the container
COPY ./src /app

# Set the default command to run the app
CMD ["python", "main.py"]
